### ISSUE TITLE
ModuleNotFoundError: No module named 'google'

### ISSUE THREAD

**Issue by gyaresu** [conda-forge/google-api-python-client-feedstock#11]
#### Hi. After a couple hours of going nuts I'm looking for some guidance on why google-api-python-client says that it installs in conda but then is not available.

Posting everything I can think of as useful here.

It's worth noting that pip (from within the conda env) also succeeded at installing 1.6.5 (the latest) but still would not import.

# Edits below as I figure out more

So `googleapiclient` is indeed installed. And `apiclient` is a an alias.

I was expecting `google.cloud` from recent examples so now I'm trying to figure out the correct way to use the [Google Cloud Natural Language API](https://cloud.google.com/natural-language/docs/reference/rest/).

Ah... ok so [this page](https://cloud.google.com/natural-language/docs/python-client-migration) details changes to the library.

And **boom**, we have a winner.

[pip install --upgrade google-cloud-natural-language](https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/language)

## "ml" environment which works for everything else
```
λ conda env list
# conda environments:
#
base                     /Users/gyaresu/miniconda3
ml                    *  /Users/gyaresu/miniconda3/envs/ml
```

## Available versions of google module
```
λ conda search google-api-python-client --channel conda-forge
Loading channels: done
Name                       Version                   Build  Channel
google-api-python-client   1.5.1                    py27_0  conda-forge
google-api-python-client   1.5.1                    py34_0  conda-forge
google-api-python-client   1.5.1                    py35_0  conda-forge
google-api-python-client   1.6.2                    py27_0  conda-forge
google-api-python-client   1.6.2                    py35_0  conda-forge
google-api-python-client   1.6.2                    py36_0  conda-forge
google-api-python-client   1.6.3                    py27_0  conda-forge
google-api-python-client   1.6.3                    py35_0  conda-forge
google-api-python-client   1.6.3                    py36_0  conda-forge
google-api-python-client   1.6.4                      py_0  conda-forge
```

## Which one are we installing?
```
λ conda list |grep google
google-api-python-client  1.6.4                      py_0    conda-forge
```

## Explicit environment install path
```
λ conda install -n ml -c conda-forge google-api-python-client
```

## Files seem to have been installed in the correct place
```
λ pwd
/Users/gyaresu/miniconda3/pkgs/google-api-python-client-1.6.4-py_0

λ ls
total 0
drwxr-xr-x    4 gyaresu  staff   128B  8 Mar 15:54 .
drwxr-xr-x  406 gyaresu  staff    13K  8 Mar 20:55 ..
drwxr-xr-x    9 gyaresu  staff   288B  8 Mar 15:54 info
drwxr-xr-x    5 gyaresu  staff   160B  8 Mar 15:54 site-packages
```

## Show environment and import in iPython
```
In [1]: print(sys.prefix)
/Users/gyaresu/miniconda3/envs/ml

In [2]: from google.cloud import language, exceptions
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-b084914f4301> in <module>()
----> 1 from google.cloud import language, exceptions

ModuleNotFoundError: No module named 'google'
```

## Conda info
```
λ conda info
     active environment: ml
    active env location : /Users/gyaresu/miniconda3/envs/ml
            shell level : 1
       user config file : /Users/gyaresu/.condarc
 populated config files : /Users/gyaresu/.condarc
          conda version : 4.4.11
    conda-build version : not installed
         python version : 3.6.3.final.0
       base environment : /Users/gyaresu/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Users/gyaresu/miniconda3/pkgs
                          /Users/gyaresu/.conda/pkgs
       envs directories : /Users/gyaresu/miniconda3/envs
                          /Users/gyaresu/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.11 requests/2.18.4 CPython/3.6.3 Darwin/17.4.0 OSX/10.13.3
                UID:GID : 502:20
             netrc file : /Users/gyaresu/.netrc
           offline mode : False
```
## Conda config
```
λ conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
aggressive_update_packages:
  - ca-certificates
  - certifi
  - openssl
allow_non_channel_urls: True
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: None
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - conda-forge
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  pkgs/main: https://repo.continuum.io
  pkgs/free: https://repo.continuum.io
  pkgs/r: https://repo.continuum.io
  pkgs/pro: https://repo.continuum.io
custom_multichannels:
  defaults: ["https://repo.continuum.io/pkgs/main", "https://repo.continuum.io/pkgs/free", "https://repo.continuum.io/pkgs/r", "https://repo.continuum.io/pkgs/pro"]
  local: []
default_channels:
  - https://repo.continuum.io/pkgs/main
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
disallow: []
download_only: False
envs_dirs:
  - /Users/gyaresu/miniconda3/envs
  - /Users/gyaresu/.conda/envs
force: False
json: False
local_repodata_ttl: 1
max_shlvl: 2
migrated_channel_aliases: []
no_dependencies: False
non_admin_enabled: True
notify_outdated_conda: True
offline: False
override_channels_enabled: True
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - /Users/gyaresu/miniconda3/pkgs
  - /Users/gyaresu/.conda/pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
report_errors: None
rollback_enabled: True
safety_checks: warn
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
use_index_cache: False
use_pip: True
verbosity: 0
whitelist_channels: []
```
